# Generated by Django 5.2.5 on 2025-08-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='point',
            new_name='points',
        ),
    ]
