# Generated by Django 5.2.5 on 2025-09-06 12:47

import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_point_team_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=team.models.GenerateTeamImagePath()),
        ),
    ]
