# Generated by Django 5.2.5 on 2025-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_projects',
            field=models.IntegerField(default=0),
        ),
    ]
